// Generated by CoffeeScript 1.8.0
(function() {
  var app, bodyParser, express, path;

  express = require('express');

  path = require('path');

  bodyParser = require('body-parser');

  app = express();

  app.set('views', path.join(__dirname, 'views'));

  app.set('view engine', 'jade');

  app.use(bodyParser.json());

  app.use(require('stylus').middleware(path.join(__dirname, 'public')));

  app.use(express["static"](path.join(__dirname, 'public')));

  app.use('/bower_components', express["static"](__dirname, '/bower_components'));

  app.get("/", function(req, res) {
    return res.render("index", {
      title: "SVG Squasher"
    });
  });

  if (app.get('env') === 'development') {
    app.use(function() {
      res.status(err.status || 500);
      return res.render('error', function() {
        return {
          message: err.message,
          error: err
        };
      });
    });
  }

  app.listen(3000, function() {
    return console.log("listening on port 3000");
  });

}).call(this);
